import { describe, it, expect } from 'vitest';
import {
  MockBamClient,
  MockBeaconClient,
  MockBoltClient,
  MockBondClient,
  type BoltEventIngest,
} from '../fixtures/mock-service-clients.js';

// ---------------------------------------------------------------------------
// Wave 3 smoke test: Bam -> Bond -> Bolt -> Beacon chain
// ---------------------------------------------------------------------------
//
// Exercises the canonical cross-product automation loop using in-process
// mocks. No docker compose stack is required. This is the scaffold Wave 4
// CI work will extend by swapping the mock clients for real HTTP clients
// pointed at a compose-provided internal network.

describe('cross-app chain (mocked)', () => {
  const ORG = 'org_test_1';
  const USER = 'usr_test_alice';

  it('Bam task.created -> Bond activity.logged -> Bolt rule-match -> Beacon entry', async () => {
    // --- Arrange ----------------------------------------------------------
    const bolt = new MockBoltClient();
    const beacon = new MockBeaconClient();

    // The Bolt automation we register below dispatches beacon_create_entry
    // on activity.logged from bond. The dispatcher routes tool names to
    // mock clients so the test can assert final-state side effects.
    const dispatchAction = async (tool: string, params: Record<string, unknown>) => {
      if (tool === 'beacon_create_entry') {
        await beacon.createEntry({
          organization_id: ORG,
          title: String(params.title ?? 'untitled'),
          body: String(params.body ?? ''),
          created_by: USER,
        });
        return;
      }
      throw new Error(`Unknown tool: ${tool}`);
    };

    // Shared publisher wraps bolt.ingest so every *service* mock emits
    // through a single point, matching the canonical publishBoltEvent
    // contract (bare event name + explicit source).
    const publish = async (event: BoltEventIngest) => {
      await bolt.ingest(event, dispatchAction);
    };

    const bam = new MockBamClient(publish);
    const bond = new MockBondClient(publish);

    // Bolt automation: when Bond emits activity.logged, create a Beacon
    // entry summarizing the linked task. In production this rule would be
    // authored in the Bolt visual rule builder and persisted as a row in
    // bolt_automations; the mock registers it directly.
    bolt.registerAutomation({
      organization_id: ORG,
      trigger_event: 'activity.logged',
      trigger_source: 'bond',
      actions: [
        {
          mcp_tool: 'beacon_create_entry',
          parameters: {
            title: 'Activity logged from chain',
            body: 'Autogenerated from Wave 3 smoke test',
          },
        },
      ],
    });

    // --- Act --------------------------------------------------------------
    // 1. Bam creates a task (publishes task.created to Bolt). No Bolt rule
    //    matches task.created in this test, so no action fires on hop 1.
    const task = await bam.createTask({
      organization_id: ORG,
      title: 'Investigate cross-app chain',
      created_by: USER,
    });

    // 2. Bond logs an activity tied to that task. This publishes
    //    activity.logged to Bolt, which matches the registered automation
    //    and dispatches beacon_create_entry.
    const activity = await bond.logActivityForTask({
      organization_id: ORG,
      task_id: task.id,
      actor_id: USER,
    });

    // --- Assert -----------------------------------------------------------
    expect(task.id).toMatch(/^tsk_/);
    expect(activity.subject_task_id).toBe(task.id);

    const executions = bolt.listExecutions();
    // Exactly one automation should have fired: the bond.activity.logged rule.
    // The bam.task.created event reaches Bolt ingest but matches nothing.
    expect(executions).toHaveLength(1);
    expect(executions[0]?.status).toBe('success');
    expect(executions[0]?.actions_run).toEqual(['beacon_create_entry']);
    expect(executions[0]?.event.event_type).toBe('activity.logged');
    expect(executions[0]?.event.source).toBe('bond');

    // And a Beacon entry should exist as the terminal side effect of
    // the whole chain.
    const entries = beacon.listEntries();
    expect(entries).toHaveLength(1);
    expect(entries[0]?.title).toBe('Activity logged from chain');
    expect(entries[0]?.organization_id).toBe(ORG);
  });

  it('bare event names and explicit source are required', async () => {
    // Regression guard: a rule registered with a prefixed event name must
    // not match a bare-name event, and vice versa. Enforces the canonical
    // naming convention documented in Cross_Product_Plan.md G3.
    const bolt = new MockBoltClient();
    bolt.registerAutomation({
      organization_id: 'org_1',
      trigger_event: 'bond.activity.logged', // prefixed (wrong)
      trigger_source: 'bond',
      actions: [{ mcp_tool: 'noop', parameters: {} }],
    });
    const results = await bolt.ingest(
      {
        event_type: 'activity.logged', // bare (right)
        source: 'bond',
        payload: {},
        organization_id: 'org_1',
        timestamp: new Date().toISOString(),
      },
      async () => {
        /* noop */
      },
    );
    expect(results).toHaveLength(0);
  });
});
