// Docker Compose platform adapter — local / self-hosted deployment.
// Zero dependencies (node:child_process, node:fs, node:path only).

import { execSync, spawn } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { bold, check, cross, dim, green, yellow, cyan, red, warn } from '../shared/colors.mjs';
import { confirm, ask } from '../shared/prompt.mjs';
import { checkDockerPrerequisites } from '../shared/prerequisites.mjs';
import { provisionCerts } from '../shared/tls.mjs';
import { runInitialIssuance, buildRenewalTask } from '../shared/letsencrypt.mjs';

const name = 'Docker Compose';
const description = 'Run everything locally with Docker (simplest)';

/**
 * Detect whether docker compose v2 is available, fall back to v1.
 */
function composeCmd() {
  try {
    execSync('docker compose version', { stdio: 'pipe' });
    return 'docker compose';
  } catch {
    return 'docker-compose';
  }
}

/**
 * Run a shell command and stream output, returning stdout on success.
 */
function runShell(cmd, opts = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, {
      shell: true,
      stdio: opts.silent ? 'pipe' : 'inherit',
      cwd: opts.cwd || process.cwd(),
    });
    let stdout = '';
    let stderr = '';
    if (opts.silent) {
      if (child.stdout) child.stdout.on('data', (d) => { stdout += d.toString(); });
      if (child.stderr) child.stderr.on('data', (d) => { stderr += d.toString(); });
    }
    child.on('close', (code) => {
      if (code === 0) resolve(stdout);
      else reject(new Error(`Command failed (exit ${code}): ${cmd}\n${stderr}`));
    });
    child.on('error', reject);
  });
}

/**
 * Sleep for ms milliseconds.
 */
function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

/**
 * Check platform-specific prerequisites.
 */
async function checkPrerequisites() {
  console.log(bold('Checking Docker Compose setup...\n'));

  // Docker + Docker Compose installed and running
  checkDockerPrerequisites();

  // Check compose file exists
  const composeFile = path.resolve(process.cwd(), 'docker-compose.yml');
  if (fs.existsSync(composeFile)) {
    console.log(`  ${check} docker-compose.yml found`);
  } else {
    console.log(`  ${cross} docker-compose.yml not found`);
    throw new Error('docker-compose.yml is missing from the repository root.');
  }

  // Docker memory (informational)
  try {
    const memRaw = execSync('docker info --format "{{.MemTotal}}"', { stdio: 'pipe', encoding: 'utf8' }).trim();
    const memBytes = parseInt(memRaw, 10);
    if (!isNaN(memBytes)) {
      const memGB = memBytes / (1024 ** 3);
      if (memGB < 4) {
        console.log(`  ${warn} Docker has ${memGB.toFixed(1)} GB RAM. 4+ GB recommended.`);
      } else {
        console.log(`  ${check} Docker memory: ${memGB.toFixed(1)} GB`);
      }
    }
  } catch {
    // non-critical
  }

  // Disk space (best effort, non-Windows)
  if (process.platform !== 'win32') {
    try {
      const df = execSync("df -h . | tail -1 | awk '{print $4}'", { stdio: 'pipe', encoding: 'utf8' }).trim();
      console.log(`  ${check} Available disk space: ${df}`);
    } catch {
      // non-critical
    }
  }

  console.log('');
  return true;
}

/**
 * Write the .env file from a key-value config object.
 */
export function writeEnvFile(envConfig) {
  const envPath = path.resolve(process.cwd(), '.env');
  const lines = [
    '# BigBlueBam environment configuration',
    `# Generated by deployment setup on ${new Date().toISOString()}`,
    '# Edit carefully -- secrets below are auto-generated.',
    '',
  ];

  const sections = {
    '# --- Core ---': ['NODE_ENV', 'DOMAIN', 'BASE_URL'],
    '# --- Database ---': ['POSTGRES_USER', 'POSTGRES_PASSWORD', 'POSTGRES_DB', 'DATABASE_URL'],
    '# --- Redis ---': ['REDIS_PASSWORD', 'REDIS_URL'],
    '# --- Auth ---': ['SESSION_SECRET', 'INTERNAL_HELPDESK_SECRET', 'INTERNAL_SERVICE_SECRET'],
    '# --- Storage ---': [
      'MINIO_ROOT_USER', 'MINIO_ROOT_PASSWORD',
      'S3_ENDPOINT', 'S3_ACCESS_KEY', 'S3_SECRET_KEY', 'S3_BUCKET', 'S3_REGION', 'S3_FORCE_PATH_STYLE',
    ],
    '# --- Vector DB ---': ['QDRANT_URL', 'QDRANT_API_KEY'],
    '# --- LiveKit ---': ['LIVEKIT_URL', 'LIVEKIT_API_KEY', 'LIVEKIT_API_SECRET'],
    '# --- Email ---': ['SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASS', 'SMTP_FROM'],
    '# --- OAuth ---': ['OAUTH_GOOGLE_CLIENT_ID', 'OAUTH_GOOGLE_CLIENT_SECRET'],
    '# --- AI ---': ['OPENAI_API_KEY', 'ANTHROPIC_API_KEY'],
  };

  for (const [header, keys] of Object.entries(sections)) {
    const sectionLines = [];
    for (const key of keys) {
      if (envConfig[key] != null && envConfig[key] !== '') {
        sectionLines.push(`${key}=${envConfig[key]}`);
      }
    }
    if (sectionLines.length > 0) {
      lines.push(header);
      lines.push(...sectionLines);
      lines.push('');
    }
  }

  // Catch any keys not in sections
  const allListed = new Set(Object.values(sections).flat());
  for (const [key, val] of Object.entries(envConfig)) {
    if (!allListed.has(key) && val != null && val !== '') {
      lines.push(`${key}=${val}`);
    }
  }

  fs.writeFileSync(envPath, lines.join('\n') + '\n', { mode: 0o600, encoding: 'utf8' });
  return envPath;
}

/**
 * Build and start the full stack.
 *
 * @param {object} envConfig - Resolved env config from main.mjs
 * @param {object} [options]
 * @param {string} [options.branch='stable'] - Git branch to track for updates.
 *   Operator is prompted in main.mjs and the choice is saved in
 *   `.deploy-state.json` so subsequent runs offer to reuse it. Defaults to
 *   `stable` — the validated production branch. Choose `main` for bleeding-
 *   edge deploys that may be unstable.
 */
async function deploy(envConfig, { branch = 'stable', tlsConfig = null } = {}) {
  const dc = composeCmd();

  // 1. Write .env
  process.stdout.write('Writing .env file... ');
  const envPath = writeEnvFile(envConfig);
  console.log(`${check} ${dim(envPath)}`);

  // 1a. Provision TLS certs (if the operator opted into TLS). Runs BEFORE
  // `docker compose up` so the frontend container's entrypoint detects
  // certs at first boot. Letsencrypt is the exception — its provisioning
  // happens AFTER nginx is up so certbot can serve the ACME challenge.
  // See docs/local-ssl-notes.md for the full picture.
  if (tlsConfig && tlsConfig.source !== 'letsencrypt') {
    const certsDir = path.resolve(process.cwd(), 'certs');
    process.stdout.write(`Provisioning TLS cert (${tlsConfig.source})... `);
    try {
      provisionCerts(tlsConfig, { domain: envConfig.DOMAIN || 'localhost', certsDir });
      console.log(`${check} ${dim(certsDir + '/local.{crt,key}')}`);
    } catch (err) {
      console.log(red('failed'));
      console.log(dim(`  ${err.message ?? err}`));
      console.log(dim('  The stack will boot but nginx will run HTTP-only until you fix this.'));
    }
  }

  // Check for updates if this is an existing installation
  const isUpgrade = fs.existsSync(path.resolve(process.cwd(), '.deploy-state.json'));
  if (isUpgrade) {
    console.log(`\nChecking for updates on ${bold(branch)}...`);
    try {
      execSync(`git fetch origin ${branch}`, { stdio: 'pipe', timeout: 15000 });
      const behind = execSync(`git rev-list HEAD..origin/${branch} --count`, { stdio: 'pipe', encoding: 'utf8' }).trim();

      if (behind !== '0') {
        console.log(`\n${yellow(`${behind} new commit(s) available on ${branch}.`)}\n`);
        try {
          const log = execSync(`git log HEAD..origin/${branch} --oneline --max-count=10`, { stdio: 'pipe', encoding: 'utf8' }).trim();
          console.log(dim(log));
          console.log('');
        } catch {}

        if (await confirm('Pull updates before rebuilding?', true)) {
          execSync(`git pull origin ${branch}`, { stdio: 'inherit' });
          console.log(`${check} Code updated.\n`);
        }
      } else {
        console.log(`${check} Already up to date.\n`);
      }
    } catch {
      console.log(dim(`  Could not check for updates on ${branch} (no git or no network).\n`));
    }
  }

  // 2. Build compose args
  const composeFiles = ['-f', 'docker-compose.yml'];
  const sitePath = path.resolve(process.cwd(), 'site');
  if (fs.existsSync(sitePath) && fs.existsSync(path.join(sitePath, 'package.json'))) {
    composeFiles.push('-f', 'docker-compose.site.yml');
    console.log(`  ${dim('site/ detected -- enabling marketing site overlay')}`);
  }
  const fileFlags = composeFiles.join(' ');

  // 3. Pull images
  console.log('\nPulling Docker images (this may take a few minutes)...\n');
  try {
    await runShell(`${dc} ${fileFlags} pull`);
    console.log(`\n${check} Images pulled`);
  } catch {
    console.log(`\n${warn} Some images could not be pulled -- they will be built locally`);
  }

  // 4. Build and start
  const gitCommit = (() => { try { return execSync('git rev-parse HEAD', { stdio: 'pipe', encoding: 'utf8' }).trim(); } catch { return 'unknown'; } })();
  const buildDate = new Date().toISOString();

  // On upgrades, we must defeat two traps that have each cost this project
  // hours of "column does not exist" debugging (see CLAUDE.md → "Applying a
  // new migration to a long-running stack"):
  //
  //   1. Docker's build cache + WSL2 file sync will silently drop new
  //      migration files from the api image context. A plain `up -d --build`
  //      is not enough — force `--no-cache` on the api image so buildkit
  //      can't reuse a stale COPY layer that's missing the new SQL file.
  //
  //   2. The `migrate` sidecar is cached via `service_completed_successfully`
  //      in docker-compose.yml, so `up -d` will NOT re-run it on an existing
  //      stack even when the api image contains new migrations. We must
  //      explicitly invoke `compose run --rm migrate` after the rebuild.
  //
  // Both happen automatically on the upgrade path so operators never have
  // to know this exists.
  if (isUpgrade) {
    console.log('\nRebuilding api image with --no-cache (ensures new migrations are baked in)...\n');
    await runShell(`GIT_COMMIT=${gitCommit} BUILD_DATE=${buildDate} ${dc} ${fileFlags} build --no-cache api`);
    console.log(`\n${check} api image rebuilt`);

    console.log('\nRunning database migrations (explicit sidecar invocation)...\n');
    try {
      // Bring postgres up first so the migrate sidecar has something to connect to.
      await runShell(`${dc} ${fileFlags} up -d postgres`);
      await runShell(`${dc} ${fileFlags} run --rm migrate`);
      console.log(`\n${check} Migrations applied`);
    } catch (err) {
      console.log(`\n${red('Migration step failed.')} ${dim(String(err?.message || err))}`);
      console.log(dim('  Check logs with: docker compose logs migrate'));
      console.log(dim('  See docs/deployment-guide.md → Updating for the manual fallback.'));
      throw err;
    }
  }

  console.log('\nBuilding and starting services...\n');
  await runShell(`GIT_COMMIT=${gitCommit} BUILD_DATE=${buildDate} ${dc} ${fileFlags} up -d --build`);
  console.log(`\n${check} All services started`);

  // 5. Wait for API to be healthy
  console.log('');
  process.stdout.write('Waiting for API to be ready... ');
  const maxWait = 120_000;
  const start = Date.now();
  let apiReady = false;

  while (Date.now() - start < maxWait) {
    try {
      execSync(
        `${dc} ${fileFlags} exec -T api node -e "fetch('http://localhost:4000/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"`,
        { stdio: 'pipe', timeout: 10_000 },
      );
      apiReady = true;
      break;
    } catch {
      await sleep(3000);
    }
  }

  if (apiReady) {
    console.log(check);
  } else {
    console.log(yellow('[timeout]'));
    console.log(dim('  The API may still be starting. Check logs with: docker compose logs -f api'));
  }

  // 6. Let's Encrypt issuance (post-up, since certbot needs nginx serving
  //    /.well-known/acme-challenge/). The other three cert sources were
  //    already provisioned in step 1a before `compose up`.
  if (tlsConfig?.source === 'letsencrypt' && tlsConfig.letsencrypt) {
    console.log('');
    console.log(bold('Issuing Let\'s Encrypt certificate...'));
    console.log(dim('  certbot will validate ' + tlsConfig.letsencrypt.domain + ' over HTTP-01.'));
    const result = runInitialIssuance({
      domain: tlsConfig.letsencrypt.domain,
      email: tlsConfig.letsencrypt.email,
      composeBin: dc,
    });
    if (result.ok) {
      console.log(`${check} Cert issued and symlinked into ${dim('./certs/local.{crt,key}')}`);
      console.log(dim('  Reloading nginx so the new cert takes effect...'));
      try {
        await runShell(`${dc} ${fileFlags} exec -T frontend nginx -s reload`);
        console.log(`${check} nginx reloaded`);
      } catch (err) {
        console.log(`${yellow('nginx reload failed; restart frontend manually:')} ${dim(`${dc} restart frontend`)}`);
      }

      // Renewal task. Print instructions instead of installing the cron
      // entry automatically — operators frequently disable system cron
      // (NAS hosts often have non-standard schedulers) and silently
      // installing into a non-running cron daemon would create a
      // false sense of "renewal handled" that breaks at month 3.
      const task = buildRenewalTask({ projectDir: process.cwd(), composeBin: dc });
      console.log('');
      console.log(bold('Auto-renewal:'));
      for (const line of task.instructions) {
        console.log(dim('  ' + line));
      }
    } else {
      console.log(`${red('Let\'s Encrypt issuance failed:')} ${dim(result.reason)}`);
      console.log(dim('  The stack is up but nginx is HTTP-only. Re-run the deploy script after'));
      console.log(dim('  resolving the issue (most often: domain not pointing at this host, or'));
      console.log(dim('  port 80 not reachable from the public internet).'));
    }
  }

  return apiReady;
}

/**
 * Run a command inside a running service container.
 */
async function runCommand(service, cmd) {
  const dc = composeCmd();
  const fullCmd = `${dc} exec -T ${service} ${cmd}`;
  return runShell(fullCmd, { silent: true });
}

/**
 * Verify a login works by hitting the auth endpoint.
 */
async function verifyLogin(email, password) {
  const dc = composeCmd();
  const escapedEmail = email.replace(/'/g, "'\\''");
  const escapedPassword = password.replace(/'/g, "'\\''");
  const script = `fetch('http://localhost:4000/b3/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'${escapedEmail}',password:'${escapedPassword}'})}).then(r=>{if(!r.ok)throw new Error('fail');process.exit(0)}).catch(()=>process.exit(1))`;
  await runShell(`${dc} exec -T api node -e "${script}"`, { silent: true });
}

/**
 * Stop the stack (no -v, data is sacred).
 */
async function stop() {
  const dc = composeCmd();
  await runShell(`${dc} down`);
}

export default {
  name,
  description,
  checkPrerequisites,
  writeEnvFile,
  deploy,
  runCommand,
  verifyLogin,
  stop,
};
